<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Seguridad" Id="{4569f4ce-7c18-43b2-b6d2-c84b9b228987}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Seguridad
VAR_INPUT
	
	CuadroPrincipalRunStop AT%I*:BOOL;
	CuadroPrincipalAutomatico AT%I*:BOOL;
	SeguridadSetas AT%I*:BOOL;
END_VAR
VAR_OUTPUT
	CuadroLedVerde AT%Q*:BOOL;
	CuadroLedAmarillo AT%Q*:BOOL;
	
	MotorSuperior_Freq  AT%Q*: UINT;
	MotorSuperior_Command AT%Q*: INT;
		
	MotorInferior_Freq  AT%Q*: UINT;
	MotorInferior_Command AT%Q*: INT;
	
	LineaReady :BOOL;
	FinTiempoTON :TON;
	
	
	
END_VAR
VAR
	FlancoRunStop:R_TRIG;
	TempCiclo:TON;
	TempRetraso:TON;
	Resultados : ResultadoCiclo;

	puesto: INT;
	Falso: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <SFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="SFCImplementationObject">
              <o n="Root" t="SFCSegment">
                <o n="ElementList" t="SFCElementList">
                  <l2 n="InnerList">
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCActionAssociation">
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"ComprobarSeguridad"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">220L</v>
                                <v n="IdParent">219L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">221L</v>
                                <v n="IdParent">219L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">222L</v>
                                <v n="IdParent">219L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">223L</v>
                                <v n="IdParent">219L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"R"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">224L</v>
                                <v n="IdParent">219L</v>
                              </o>
                            </l2>
                            <v n="Id">219L</v>
                            <v n="IdParent">10L</v>
                          </o>
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"GVL.SemaforoRojo"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">410L</v>
                                <v n="IdParent">409L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">411L</v>
                                <v n="IdParent">409L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">412L</v>
                                <v n="IdParent">409L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">413L</v>
                                <v n="IdParent">409L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"N"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">414L</v>
                                <v n="IdParent">409L</v>
                              </o>
                            </l2>
                            <v n="Id">409L</v>
                            <v n="IdParent">10L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">11L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">12L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">13L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">14L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"TRUE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">15L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">16L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">17L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">18L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Init_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">19L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">20L</v>
                          <v n="IdParent">10L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">21L</v>
                          <v n="IdParent">10L</v>
                        </o>
                      </l2>
                      <v n="Id">10L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"Init__to__EsperaRunStop"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"SeguridadSetas"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">23L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">24L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">25L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">26L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">27L</v>
                          <v n="IdParent">22L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">28L</v>
                          <v n="IdParent">22L</v>
                        </o>
                      </l2>
                      <v n="Id">22L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCActionAssociation">
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"ComprobarSeguridad"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">378L</v>
                                <v n="IdParent">377L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">379L</v>
                                <v n="IdParent">377L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">380L</v>
                                <v n="IdParent">377L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">381L</v>
                                <v n="IdParent">377L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"S"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">382L</v>
                                <v n="IdParent">377L</v>
                              </o>
                            </l2>
                            <v n="Id">377L</v>
                            <v n="IdParent">50L</v>
                          </o>
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"GVL.SeguridadOK"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">188L</v>
                                <v n="IdParent">187L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">189L</v>
                                <v n="IdParent">187L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">190L</v>
                                <v n="IdParent">187L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">191L</v>
                                <v n="IdParent">187L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"N"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">192L</v>
                                <v n="IdParent">187L</v>
                              </o>
                            </l2>
                            <v n="Id">187L</v>
                            <v n="IdParent">50L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"EsperaRunStop"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">51L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">52L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">53L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">54L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">55L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">56L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"T#1s"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">57L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">58L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"EsperaRunStop_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">59L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">60L</v>
                          <v n="IdParent">50L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">61L</v>
                          <v n="IdParent">50L</v>
                        </o>
                      </l2>
                      <v n="Id">50L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCTransition">
                      <v n="VariableName">"EsperaRunStop__to__ModoRUN"</v>
                      <n n="EmbeddedTransition" />
                      <l2 n="EmbeddedTransitionProperties" />
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"FlancoRunStop.Q"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">194L</v>
                          <v n="IdParent">193L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">195L</v>
                          <v n="IdParent">193L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">196L</v>
                          <v n="IdParent">193L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">197L</v>
                          <v n="IdParent">193L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">198L</v>
                          <v n="IdParent">193L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">199L</v>
                          <v n="IdParent">193L</v>
                        </o>
                      </l2>
                      <v n="Id">193L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCStep">
                      <n n="EmbeddedMainAction" />
                      <n n="EmbeddedEntryAction" />
                      <n n="EmbeddedExitAction" />
                      <l2 n="EmbeddedMainActionProperties" />
                      <l2 n="EmbeddedEntryActionProperties" />
                      <l2 n="EmbeddedExitActionProperties" />
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCActionAssociation">
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"GVL.ModoRun"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">358L</v>
                                <v n="IdParent">357L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">359L</v>
                                <v n="IdParent">357L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">360L</v>
                                <v n="IdParent">357L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">361L</v>
                                <v n="IdParent">357L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"N"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">362L</v>
                                <v n="IdParent">357L</v>
                              </o>
                            </l2>
                            <v n="Id">357L</v>
                            <v n="IdParent">76L</v>
                          </o>
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"GVL.SeguridadOK"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">182L</v>
                                <v n="IdParent">181L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">183L</v>
                                <v n="IdParent">181L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">184L</v>
                                <v n="IdParent">181L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">185L</v>
                                <v n="IdParent">181L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"N"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">186L</v>
                                <v n="IdParent">181L</v>
                              </o>
                            </l2>
                            <v n="Id">181L</v>
                            <v n="IdParent">76L</v>
                          </o>
                          <o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"CuadroLedAmarillo"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">214L</v>
                                <v n="IdParent">213L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">215L</v>
                                <v n="IdParent">213L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">216L</v>
                                <v n="IdParent">213L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                <o n="Value" t="EnumValue">
                                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                  <n n="BaseType" />
                                  <v n="Value">"0"</v>
                                  <v n="DefaultValue">"0"</v>
                                </o>
                                <v n="Id">217L</v>
                                <v n="IdParent">213L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">"N"</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">218L</v>
                                <v n="IdParent">213L</v>
                              </o>
                            </l2>
                            <v n="Id">213L</v>
                            <v n="IdParent">76L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"ModoRUN"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">77L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">78L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">79L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                          <o n="Value" t="EnumValue">
                            <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                            <n n="BaseType" />
                            <v n="Value">"0"</v>
                            <v n="DefaultValue">"0"</v>
                          </o>
                          <v n="Id">80L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">81L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">82L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"T#1s"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">83L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">84L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"ModoRUN_active"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">85L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">86L</v>
                          <v n="IdParent">76L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">87L</v>
                          <v n="IdParent">76L</v>
                        </o>
                      </l2>
                      <v n="Id">76L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCBranch">
                      <o n="ElementList" t="SFCElementList">
                        <l2 n="InnerList" cet="SFCSegment">
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch0__ModoRUN__to__ReseteaPuestos"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"Not CuadroPrincipalRunStop"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">278L</v>
                                      <v n="IdParent">277L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">279L</v>
                                      <v n="IdParent">277L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">280L</v>
                                      <v n="IdParent">277L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">281L</v>
                                      <v n="IdParent">277L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">282L</v>
                                      <v n="IdParent">277L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">283L</v>
                                      <v n="IdParent">277L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">277L</v>
                                  <v n="IdParent">566L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" />
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"ReseteaPuestos"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">489L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">490L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">491L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">492L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">493L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">494L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"T#1s"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">495L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">496L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"ReseteaPuestos_active"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">497L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">498L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">499L</v>
                                      <v n="IdParent">488L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">488L</v>
                                  <v n="IdParent">566L</v>
                                </o>
                                <o t="SFCTransition">
                                  <v n="VariableName">"ReseteaPuestos__to__EsperaRunStop"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"True"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">501L</v>
                                      <v n="IdParent">500L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">502L</v>
                                      <v n="IdParent">500L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">503L</v>
                                      <v n="IdParent">500L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">504L</v>
                                      <v n="IdParent">500L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">505L</v>
                                      <v n="IdParent">500L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">506L</v>
                                      <v n="IdParent">500L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">500L</v>
                                  <v n="IdParent">566L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">567L</v>
                                <v n="IdParent">566L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">568L</v>
                                <v n="IdParent">566L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">569L</v>
                                <v n="IdParent">566L</v>
                              </o>
                            </l2>
                            <v n="Id">566L</v>
                            <v n="IdParent">561L</v>
                          </o>
                          <o>
                            <o n="ElementList" t="SFCElementList">
                              <l2 n="InnerList">
                                <o t="SFCTransition">
                                  <v n="VariableName">"Branch1__ModoRUN__to__PasaUnPalet"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"LineaReady and CuadroPrincipalAutomatico"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">575L</v>
                                      <v n="IdParent">574L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">576L</v>
                                      <v n="IdParent">574L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">577L</v>
                                      <v n="IdParent">574L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">578L</v>
                                      <v n="IdParent">574L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">579L</v>
                                      <v n="IdParent">574L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">580L</v>
                                      <v n="IdParent">574L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">574L</v>
                                  <v n="IdParent">570L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" cet="SFCActionAssociation">
                                      <o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">"gvl.ModoRun"</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">840L</v>
                                            <v n="IdParent">839L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">841L</v>
                                            <v n="IdParent">839L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">842L</v>
                                            <v n="IdParent">839L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                            <o n="Value" t="EnumValue">
                                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                              <n n="BaseType" />
                                              <v n="Value">"0"</v>
                                              <v n="DefaultValue">"0"</v>
                                            </o>
                                            <v n="Id">843L</v>
                                            <v n="IdParent">839L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">"N"</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">844L</v>
                                            <v n="IdParent">839L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">839L</v>
                                        <v n="IdParent">820L</v>
                                      </o>
                                      <o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">"gvl.FinCiclo"</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">846L</v>
                                            <v n="IdParent">845L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">847L</v>
                                            <v n="IdParent">845L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">848L</v>
                                            <v n="IdParent">845L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                            <o n="Value" t="EnumValue">
                                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                              <n n="BaseType" />
                                              <v n="Value">"0"</v>
                                              <v n="DefaultValue">"0"</v>
                                            </o>
                                            <v n="Id">849L</v>
                                            <v n="IdParent">845L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">"N"</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">850L</v>
                                            <v n="IdParent">845L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">845L</v>
                                        <v n="IdParent">820L</v>
                                      </o>
                                    </l2>
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"PasaUnPalet"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">821L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">822L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">823L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">824L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">825L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">826L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"T#3s"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">827L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">828L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">829L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">830L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">831L</v>
                                      <v n="IdParent">820L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">820L</v>
                                  <v n="IdParent">570L</v>
                                </o>
                                <o t="SFCTransition">
                                  <v n="VariableName">"PasaUnPalet__to__CicloLinea"</v>
                                  <n n="EmbeddedTransition" />
                                  <l2 n="EmbeddedTransitionProperties" />
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"True"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">833L</v>
                                      <v n="IdParent">832L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">834L</v>
                                      <v n="IdParent">832L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">835L</v>
                                      <v n="IdParent">832L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">836L</v>
                                      <v n="IdParent">832L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">837L</v>
                                      <v n="IdParent">832L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">838L</v>
                                      <v n="IdParent">832L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">832L</v>
                                  <v n="IdParent">570L</v>
                                </o>
                                <o t="SFCStep">
                                  <n n="EmbeddedMainAction" />
                                  <n n="EmbeddedEntryAction" />
                                  <n n="EmbeddedExitAction" />
                                  <l2 n="EmbeddedMainActionProperties" />
                                  <l2 n="EmbeddedEntryActionProperties" />
                                  <l2 n="EmbeddedExitActionProperties" />
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" cet="SFCActionAssociation">
                                      <o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">"gvl.ModoRun"</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">681L</v>
                                            <v n="IdParent">680L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">682L</v>
                                            <v n="IdParent">680L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">683L</v>
                                            <v n="IdParent">680L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                            <o n="Value" t="EnumValue">
                                              <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                              <n n="BaseType" />
                                              <v n="Value">"0"</v>
                                              <v n="DefaultValue">"0"</v>
                                            </o>
                                            <v n="Id">684L</v>
                                            <v n="IdParent">680L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">"N"</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">685L</v>
                                            <v n="IdParent">680L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">680L</v>
                                        <v n="IdParent">581L</v>
                                      </o>
                                    </l2>
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"CicloLinea"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">582L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">583L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">584L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                      <o n="Value" t="EnumValue">
                                        <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                        <n n="BaseType" />
                                        <v n="Value">"0"</v>
                                        <v n="DefaultValue">"0"</v>
                                      </o>
                                      <v n="Id">585L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">586L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">587L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"T#4s"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">588L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">589L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"CicloLinea_active"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">590L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"CicloLinea_entry"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">591L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">592L</v>
                                      <v n="IdParent">581L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">581L</v>
                                  <v n="IdParent">570L</v>
                                </o>
                                <o t="SFCBranch">
                                  <o n="ElementList" t="SFCElementList">
                                    <l2 n="InnerList" cet="SFCSegment">
                                      <o>
                                        <o n="ElementList" t="SFCElementList">
                                          <l2 n="InnerList">
                                            <o t="SFCTransition">
                                              <v n="VariableName">"Branch1_0__CicloLinea__to__Fin"</v>
                                              <n n="EmbeddedTransition" />
                                              <l2 n="EmbeddedTransitionProperties" />
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"TempCiclo.Q and LineaReady"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">594L</v>
                                                  <v n="IdParent">593L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">595L</v>
                                                  <v n="IdParent">593L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">596L</v>
                                                  <v n="IdParent">593L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">597L</v>
                                                  <v n="IdParent">593L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">598L</v>
                                                  <v n="IdParent">593L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">599L</v>
                                                  <v n="IdParent">593L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">593L</v>
                                              <v n="IdParent">642L</v>
                                            </o>
                                            <o t="SFCStep">
                                              <n n="EmbeddedMainAction" />
                                              <n n="EmbeddedEntryAction" />
                                              <n n="EmbeddedExitAction" />
                                              <l2 n="EmbeddedMainActionProperties" />
                                              <l2 n="EmbeddedEntryActionProperties" />
                                              <l2 n="EmbeddedExitActionProperties" />
                                              <o n="ElementList" t="SFCElementList">
                                                <l2 n="InnerList" cet="SFCActionAssociation">
                                                  <o>
                                                    <l2 n="Attributes" cet="SFCAttribute">
                                                      <o>
                                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                        <o n="Value" t="StringValue">
                                                          <v n="Value">"gvl.ModoRun"</v>
                                                          <v n="DefaultValue">""</v>
                                                        </o>
                                                        <v n="Id">687L</v>
                                                        <v n="IdParent">686L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                        <o n="Value" t="StringValue">
                                                          <v n="Value">""</v>
                                                          <v n="DefaultValue">""</v>
                                                        </o>
                                                        <v n="Id">688L</v>
                                                        <v n="IdParent">686L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                        <o n="Value" t="BoolValue">
                                                          <v n="Value">"FALSE"</v>
                                                          <v n="DefaultValue">"FALSE"</v>
                                                        </o>
                                                        <v n="Id">689L</v>
                                                        <v n="IdParent">686L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                        <o n="Value" t="EnumValue">
                                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                          <n n="BaseType" />
                                                          <v n="Value">"0"</v>
                                                          <v n="DefaultValue">"0"</v>
                                                        </o>
                                                        <v n="Id">690L</v>
                                                        <v n="IdParent">686L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                                        <o n="Value" t="StringValue">
                                                          <v n="Value">"N"</v>
                                                          <v n="DefaultValue">""</v>
                                                        </o>
                                                        <v n="Id">691L</v>
                                                        <v n="IdParent">686L</v>
                                                      </o>
                                                    </l2>
                                                    <v n="Id">686L</v>
                                                    <v n="IdParent">612L</v>
                                                  </o>
                                                  <o>
                                                    <l2 n="Attributes" cet="SFCAttribute">
                                                      <o>
                                                        <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                        <o n="Value" t="StringValue">
                                                          <v n="Value">"gvl.FinCiclo"</v>
                                                          <v n="DefaultValue">""</v>
                                                        </o>
                                                        <v n="Id">721L</v>
                                                        <v n="IdParent">720L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                        <o n="Value" t="StringValue">
                                                          <v n="Value">""</v>
                                                          <v n="DefaultValue">""</v>
                                                        </o>
                                                        <v n="Id">722L</v>
                                                        <v n="IdParent">720L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                        <o n="Value" t="BoolValue">
                                                          <v n="Value">"FALSE"</v>
                                                          <v n="DefaultValue">"FALSE"</v>
                                                        </o>
                                                        <v n="Id">723L</v>
                                                        <v n="IdParent">720L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                        <o n="Value" t="EnumValue">
                                                          <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                          <n n="BaseType" />
                                                          <v n="Value">"0"</v>
                                                          <v n="DefaultValue">"0"</v>
                                                        </o>
                                                        <v n="Id">724L</v>
                                                        <v n="IdParent">720L</v>
                                                      </o>
                                                      <o>
                                                        <v n="AttributeId">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                                                        <o n="Value" t="StringValue">
                                                          <v n="Value">"N"</v>
                                                          <v n="DefaultValue">""</v>
                                                        </o>
                                                        <v n="Id">725L</v>
                                                        <v n="IdParent">720L</v>
                                                      </o>
                                                    </l2>
                                                    <v n="Id">720L</v>
                                                    <v n="IdParent">612L</v>
                                                  </o>
                                                </l2>
                                              </o>
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"Fin"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">613L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">614L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">615L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">616L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">617L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">618L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"T#3s"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">619L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">620L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">621L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">622L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"ControlDeFallos"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">623L</v>
                                                  <v n="IdParent">612L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">612L</v>
                                              <v n="IdParent">642L</v>
                                            </o>
                                            <o t="SFCTransition">
                                              <v n="VariableName">"Fin__to__Ciclolinea"</v>
                                              <n n="EmbeddedTransition" />
                                              <l2 n="EmbeddedTransitionProperties" />
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"True"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">625L</v>
                                                  <v n="IdParent">624L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">626L</v>
                                                  <v n="IdParent">624L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">627L</v>
                                                  <v n="IdParent">624L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">628L</v>
                                                  <v n="IdParent">624L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">629L</v>
                                                  <v n="IdParent">624L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">630L</v>
                                                  <v n="IdParent">624L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">624L</v>
                                              <v n="IdParent">642L</v>
                                            </o>
                                            <o t="SFCJump">
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"Ciclolinea"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">693L</v>
                                                  <v n="IdParent">692L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">694L</v>
                                                  <v n="IdParent">692L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">695L</v>
                                                  <v n="IdParent">692L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">692L</v>
                                              <v n="IdParent">642L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">643L</v>
                                            <v n="IdParent">642L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">644L</v>
                                            <v n="IdParent">642L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">645L</v>
                                            <v n="IdParent">642L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">642L</v>
                                        <v n="IdParent">637L</v>
                                      </o>
                                      <o>
                                        <o n="ElementList" t="SFCElementList">
                                          <l2 n="InnerList">
                                            <o t="SFCTransition">
                                              <v n="VariableName">"Branch1_1__CicloLinea__to__ReseteaPuestos"</v>
                                              <n n="EmbeddedTransition" />
                                              <l2 n="EmbeddedTransitionProperties" />
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"Not CuadroPrincipalRunSTop"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">651L</v>
                                                  <v n="IdParent">650L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">652L</v>
                                                  <v n="IdParent">650L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">653L</v>
                                                  <v n="IdParent">650L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">654L</v>
                                                  <v n="IdParent">650L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">655L</v>
                                                  <v n="IdParent">650L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">656L</v>
                                                  <v n="IdParent">650L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">650L</v>
                                              <v n="IdParent">646L</v>
                                            </o>
                                            <o t="SFCJump">
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"ReseteaPuestos"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">677L</v>
                                                  <v n="IdParent">676L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">678L</v>
                                                  <v n="IdParent">676L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">679L</v>
                                                  <v n="IdParent">676L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">676L</v>
                                              <v n="IdParent">646L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">647L</v>
                                            <v n="IdParent">646L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">648L</v>
                                            <v n="IdParent">646L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">649L</v>
                                            <v n="IdParent">646L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">646L</v>
                                        <v n="IdParent">637L</v>
                                      </o>
                                      <o>
                                        <o n="ElementList" t="SFCElementList">
                                          <l2 n="InnerList">
                                            <o t="SFCTransition">
                                              <v n="VariableName">"Branch1_2__CicloLinea__to__ModoRun"</v>
                                              <n n="EmbeddedTransition" />
                                              <l2 n="EmbeddedTransitionProperties" />
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"Not CuadroPrincipalAutomatico"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">791L</v>
                                                  <v n="IdParent">790L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">792L</v>
                                                  <v n="IdParent">790L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">793L</v>
                                                  <v n="IdParent">790L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">794L</v>
                                                  <v n="IdParent">790L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">795L</v>
                                                  <v n="IdParent">790L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                                                  <o n="Value" t="EnumValue">
                                                    <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                                                    <n n="BaseType" />
                                                    <v n="Value">"0"</v>
                                                    <v n="DefaultValue">"0"</v>
                                                  </o>
                                                  <v n="Id">796L</v>
                                                  <v n="IdParent">790L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">790L</v>
                                              <v n="IdParent">786L</v>
                                            </o>
                                            <o t="SFCJump">
                                              <l2 n="Attributes" cet="SFCAttribute">
                                                <o>
                                                  <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">"ModoRun"</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">817L</v>
                                                  <v n="IdParent">816L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                                  <o n="Value" t="StringValue">
                                                    <v n="Value">""</v>
                                                    <v n="DefaultValue">""</v>
                                                  </o>
                                                  <v n="Id">818L</v>
                                                  <v n="IdParent">816L</v>
                                                </o>
                                                <o>
                                                  <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                                  <o n="Value" t="BoolValue">
                                                    <v n="Value">"FALSE"</v>
                                                    <v n="DefaultValue">"FALSE"</v>
                                                  </o>
                                                  <v n="Id">819L</v>
                                                  <v n="IdParent">816L</v>
                                                </o>
                                              </l2>
                                              <v n="Id">816L</v>
                                              <v n="IdParent">786L</v>
                                            </o>
                                          </l2>
                                        </o>
                                        <l2 n="Attributes" cet="SFCAttribute">
                                          <o>
                                            <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">787L</v>
                                            <v n="IdParent">786L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                            <o n="Value" t="StringValue">
                                              <v n="Value">""</v>
                                              <v n="DefaultValue">""</v>
                                            </o>
                                            <v n="Id">788L</v>
                                            <v n="IdParent">786L</v>
                                          </o>
                                          <o>
                                            <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                            <o n="Value" t="BoolValue">
                                              <v n="Value">"FALSE"</v>
                                              <v n="DefaultValue">"FALSE"</v>
                                            </o>
                                            <v n="Id">789L</v>
                                            <v n="IdParent">786L</v>
                                          </o>
                                        </l2>
                                        <v n="Id">786L</v>
                                        <v n="IdParent">637L</v>
                                      </o>
                                    </l2>
                                  </o>
                                  <l2 n="Attributes" cet="SFCAttribute">
                                    <o>
                                      <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">"Branch1"</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">638L</v>
                                      <v n="IdParent">637L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                      <o n="Value" t="StringValue">
                                        <v n="Value">""</v>
                                        <v n="DefaultValue">""</v>
                                      </o>
                                      <v n="Id">639L</v>
                                      <v n="IdParent">637L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">640L</v>
                                      <v n="IdParent">637L</v>
                                    </o>
                                    <o>
                                      <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                                      <o n="Value" t="BoolValue">
                                        <v n="Value">"FALSE"</v>
                                        <v n="DefaultValue">"FALSE"</v>
                                      </o>
                                      <v n="Id">641L</v>
                                      <v n="IdParent">637L</v>
                                    </o>
                                  </l2>
                                  <v n="Id">637L</v>
                                  <v n="IdParent">570L</v>
                                </o>
                              </l2>
                            </o>
                            <l2 n="Attributes" cet="SFCAttribute">
                              <o>
                                <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">571L</v>
                                <v n="IdParent">570L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                                <o n="Value" t="StringValue">
                                  <v n="Value">""</v>
                                  <v n="DefaultValue">""</v>
                                </o>
                                <v n="Id">572L</v>
                                <v n="IdParent">570L</v>
                              </o>
                              <o>
                                <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                                <o n="Value" t="BoolValue">
                                  <v n="Value">"FALSE"</v>
                                  <v n="DefaultValue">"FALSE"</v>
                                </o>
                                <v n="Id">573L</v>
                                <v n="IdParent">570L</v>
                              </o>
                            </l2>
                            <v n="Id">570L</v>
                            <v n="IdParent">561L</v>
                          </o>
                        </l2>
                      </o>
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"Branch0"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">562L</v>
                          <v n="IdParent">561L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">563L</v>
                          <v n="IdParent">561L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">564L</v>
                          <v n="IdParent">561L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">565L</v>
                          <v n="IdParent">561L</v>
                        </o>
                      </l2>
                      <v n="Id">561L</v>
                      <v n="IdParent">9L</v>
                    </o>
                    <o t="SFCJump">
                      <l2 n="Attributes" cet="SFCAttribute">
                        <o>
                          <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">"EsperaRunStop"</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">304L</v>
                          <v n="IdParent">303L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                          <o n="Value" t="StringValue">
                            <v n="Value">""</v>
                            <v n="DefaultValue">""</v>
                          </o>
                          <v n="Id">305L</v>
                          <v n="IdParent">303L</v>
                        </o>
                        <o>
                          <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                          <o n="Value" t="BoolValue">
                            <v n="Value">"FALSE"</v>
                            <v n="DefaultValue">"FALSE"</v>
                          </o>
                          <v n="Id">306L</v>
                          <v n="IdParent">303L</v>
                        </o>
                      </l2>
                      <v n="Id">303L</v>
                      <v n="IdParent">9L</v>
                    </o>
                  </l2>
                </o>
                <l2 n="Attributes" cet="SFCAttribute">
                  <o>
                    <v n="AttributeId">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">383L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                    <o n="Value" t="StringValue">
                      <v n="Value">""</v>
                      <v n="DefaultValue">""</v>
                    </o>
                    <v n="Id">384L</v>
                    <v n="IdParent">9L</v>
                  </o>
                  <o>
                    <v n="AttributeId">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                    <o n="Value" t="BoolValue">
                      <v n="Value">"FALSE"</v>
                      <v n="DefaultValue">"FALSE"</v>
                    </o>
                    <v n="Id">385L</v>
                    <v n="IdParent">9L</v>
                  </o>
                </l2>
                <v n="Id">9L</v>
                <v n="IdParent">-1L</v>
              </o>
              <d2 n="Categories" ckt="Guid" cvt="SFCAttributeCategory">
                <v>1c5c6e05-2bb7-4258-bcee-fd16a540c63c</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Identifier">"Specific"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Element type specific properties"</v>
                </o>
                <v>20f0fc67-978d-438b-979f-eef294f34ee4</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Identifier">"Actions"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Action definitions"</v>
                </o>
                <v>6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Identifier">"Common"</v>
                  <v n="Parent">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="Description">"Common properties"</v>
                </o>
                <v>d336ba06-8a67-4e6b-9697-50f83ba6bdde</v>
                <o>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Identifier">"Times"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Time definitions"</v>
                </o>
              </d2>
              <d2 n="Attributes" ckt="Guid" cvt="SFCAttributeDescription">
                <v>01580b27-6378-448b-8ecb-0e4b795b58d6</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">true</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{01580b27-6378-448b-8ecb-0e4b795b58d6}</v>
                  <v n="Identifier">"Exclude"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Exclude this element from build"</v>
                </o>
                <v>23bdaa98-72ec-41f7-817b-9dede5697086</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{23bdaa98-72ec-41f7-817b-9dede5697086}</v>
                  <v n="Identifier">"Parallel"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the branch to parallel mode"</v>
                </o>
                <v>38391c6d-6d4a-42f8-8ee7-9f45e5adafa8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{38391c6d-6d4a-42f8-8ee7-9f45e5adafa8}</v>
                  <v n="Identifier">"Name"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Name of the element"</v>
                </o>
                <v>62e1754b-7629-4e63-9cec-10ae0c536f1f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{62e1754b-7629-4e63-9cec-10ae0c536f1f}</v>
                  <v n="Identifier">"Duplication"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Copies the implementation of step actions or transitions with the element. Otherwise, copies the reference to an existing implementation."</v>
                </o>
                <v>6844a48e-46c2-4cc8-a185-a478f3b99cc0</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{6844a48e-46c2-4cc8-a185-a478f3b99cc0}</v>
                  <v n="Identifier">"InitStep"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Sets the step as the initial step"</v>
                </o>
                <v>700a583f-b4d4-43e4-8c14-629c7cd3bec8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{700a583f-b4d4-43e4-8c14-629c7cd3bec8}</v>
                  <v n="Identifier">"MainAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is active"</v>
                </o>
                <v>7d894980-aeea-405c-a0f6-e2b26429c58f</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">true</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{7d894980-aeea-405c-a0f6-e2b26429c58f}</v>
                  <v n="Identifier">"Comment"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Comment of the element"</v>
                </o>
                <v>8294df19-5962-4dee-a874-1051dabb0e3e</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{8294df19-5962-4dee-a874-1051dabb0e3e}</v>
                  <v n="Identifier">"Monitoring"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Indicates transition monitoring setting."</v>
                </o>
                <v>a2621e18-7de3-4ea6-ae6d-89e9e0b7befd</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a2621e18-7de3-4ea6-ae6d-89e9e0b7befd}</v>
                  <v n="Identifier">"ExitAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is deactivated"</v>
                </o>
                <v>a6b08bd8-b696-47e3-9cbf-7408b61c9ff8</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{a6b08bd8-b696-47e3-9cbf-7408b61c9ff8}</v>
                  <v n="Identifier">"EntryAction"</v>
                  <v n="Parent">{20f0fc67-978d-438b-979f-eef294f34ee4}</v>
                  <v n="Description">"Name of the action to be called if the step is activated"</v>
                </o>
                <v>b693554c-1b01-4a8d-afde-9e3a46f7465d</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{b693554c-1b01-4a8d-afde-9e3a46f7465d}</v>
                  <v n="Identifier">"MaxTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the maximal active time for the step"</v>
                </o>
                <v>bc882c11-1e91-4dd8-a6b8-2075724ed18b</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{bc882c11-1e91-4dd8-a6b8-2075724ed18b}</v>
                  <v n="Identifier">"Symbol"</v>
                  <v n="Parent">{6f37ae05-4d8f-4ddc-9e69-c0e6bd6962c2}</v>
                  <v n="Description">"Symbol configuration setting of the element"</v>
                </o>
                <v>cacf1a68-236e-47c2-b7b1-1cf9199718cb</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">true</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{cacf1a68-236e-47c2-b7b1-1cf9199718cb}</v>
                  <v n="Identifier">"MinTime"</v>
                  <v n="Parent">{d336ba06-8a67-4e6b-9697-50f83ba6bdde}</v>
                  <v n="Description">"Defines the minimal active time for the step"</v>
                </o>
                <v>e174fc0d-80b0-4a9e-a530-ca239c249a50</v>
                <o>
                  <v n="ReadOnly">false</v>
                  <v n="Hidden">false</v>
                  <v n="EditorVisibility">false</v>
                  <v n="MultiLineEdit">false</v>
                  <v n="Factory">{11e03a9d-fc7b-4112-850c-ae33fb04a2b4}</v>
                  <v n="Id">{e174fc0d-80b0-4a9e-a530-ca239c249a50}</v>
                  <v n="Identifier">"Qualifier"</v>
                  <v n="Parent">{1c5c6e05-2bb7-4258-bcee-fd16a540c63c}</v>
                  <v n="Description">"Qualifier of the action association"</v>
                </o>
              </d2>
              <d2 n="EnumTemplates" ckt="Guid" cvt="EnumValueTemplate">
                <v>6ecff51c-9b8f-4338-aab0-67c2b31b07e9</v>
                <o>
                  <v n="TemplateGuid">{6ecff51c-9b8f-4338-aab0-67c2b31b07e9}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Variable"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"Variable"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Call"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Call"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
                <v>79a4fdd5-c859-4de4-aa8d-c03372c880c2</v>
                <o>
                  <v n="TemplateGuid">{79a4fdd5-c859-4de4-aa8d-c03372c880c2}</v>
                  <l n="Values" t="ArrayList" cet="EnumEntry">
                    <o>
                      <v n="Identifier">"Unspecified"</v>
                      <v n="Value">0L</v>
                      <v n="Key">"Unspecified"</v>
                    </o>
                    <o>
                      <v n="Identifier">"None"</v>
                      <v n="Value">1L</v>
                      <v n="Key">"None"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Read"</v>
                      <v n="Value">2L</v>
                      <v n="Key">"Read"</v>
                    </o>
                    <o>
                      <v n="Identifier">"Write"</v>
                      <v n="Value">3L</v>
                      <v n="Key">"Write"</v>
                    </o>
                    <o>
                      <v n="Identifier">"ReadWrite"</v>
                      <v n="Value">4L</v>
                      <v n="Key">"ReadWrite"</v>
                    </o>
                  </l>
                  <v n="BaseType">"INT"</v>
                </o>
              </d2>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolValue">{89e1c7bb-c9f8-4be3-b8a7-019cdbb9f7e8}</Type>
            <Type n="EnumEntry">{4185e6da-1717-44c9-b705-102861764479}</Type>
            <Type n="EnumValue">{4dd7572b-4b9d-4d35-963e-6a34a4aaa5c1}</Type>
            <Type n="EnumValueTemplate">{d6bfe4f0-d62f-4b5f-9f95-2bbeb1950e28}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="SFCActionAssociation">{a94bb75d-5fb3-40ad-9d01-41d5b980784d}</Type>
            <Type n="SFCAttribute">{21f3f16e-04fa-4637-b6b7-d84e4192e99f}</Type>
            <Type n="SFCAttributeCategory">{679adacf-f2a4-4167-a3f7-d21cfc5d451f}</Type>
            <Type n="SFCAttributeDescription">{d851789d-af2c-4990-9d48-a7bdc9181773}</Type>
            <Type n="SFCBranch">{e221b778-bb8f-44ba-8a6a-f796287d4e62}</Type>
            <Type n="SFCElementList">{587d6556-cfe6-4e76-9cc9-fc0daf0c8c29}</Type>
            <Type n="SFCImplementationObject">{74f81948-1328-492c-b6c1-a9ea72048b28}</Type>
            <Type n="SFCJump">{7e39ac27-154f-419a-a255-6a6cf37d5ed0}</Type>
            <Type n="SFCSegment">{f1db7f6f-4774-46a6-ad9b-a94414f875fc}</Type>
            <Type n="SFCStep">{86ee92a2-d863-4136-be27-82b36d84211c}</Type>
            <Type n="SFCTransition">{4ecb29e8-a90a-4646-84ac-2ff54215ab29}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringValue">{778c8bac-3fa0-41e1-99d3-2b628d12d3e5}</Type>
          </TypeList>
        </XmlArchive>
      </SFC>
    </Implementation>
    <Action Name="CicloLinea_active" Id="{10c95d75-f399-4dc5-aae0-0b73a7f56992}">
      <Implementation>
        <ST><![CDATA[TempCiclo(IN:=TRUE);
TempRetraso(IN:=TempCiclo.Q);

gvl.SemaforoVerde := TRUE;

IF (    (ElevadorInicioLinea.Ready OR gvl.ModoDobleCarga)///no esperamos por elevador inicio en modo doble carga
	AND (ElevadorFinLinea.ready OR GVL.Puesto92.EsperandoPalet ) //si el ultimo  puesto no tieen palet no esperamos por elevador fin
	AND GVL.Puesto11.FinPuesto AND
		GVL.Puesto12.FinPuesto AND
		GVL.Puesto21.FinPuesto AND
		GVL.Puesto22.FinPuesto AND
		GVL.Puesto31.FinPuesto AND
		GVL.Puesto32.FinPuesto AND
		GVL.Puesto41.FinPuesto AND
		GVL.Puesto42.FinPuesto AND
		GVL.Puesto51.FinPuesto AND
		GVL.Puesto52.FinPuesto AND
		GVL.Puesto61.FinPuesto AND
		GVL.Puesto62.FinPuesto AND
		GVL.Puesto71.FinPuesto AND
		GVL.Puesto72.FinPuesto AND
		GVL.Puesto81.FinPuesto AND
		GVL.Puesto82.FinPuesto AND
		GVL.Puesto91.FinPuesto AND
		(gvl.Puesto81.LuzRoja = FALSE) AND
		(GVL.Puesto92.FinPuesto OR gvl.ModoDobleCarga))
THEN
		LineaReady := TRUE;
		gvl.SemaforoAmarillo :=  FALSE;
ELSE 
	    LineaReady := FALSE;
		gvl.SemaforoAmarillo := TempCiclo.Q;
END_IF


IF TempCiclo.Q AND NOT Lineaready THEN

		IF NOT  GVL.Puesto11.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[1] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto12.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[2] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto21.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[3] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		if not 	GVL.Puesto22.FinPuesto then gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[4] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto31.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[5] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto32.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[6] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto41.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[7] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto42.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[8] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto51.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[9] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto52.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[10] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto61.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[11] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto62.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[12] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto71.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[13] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		if not 	GVL.Puesto72.FinPuesto then gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[14] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto81.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[15] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto82.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[16] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto91.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[17] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 
		IF NOT 	GVL.Puesto92.FinPuesto THEN gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[18] := TIME_TO_INT(TempRetraso.ET/1000); END_IF 

END_IF


IF GVL.Puesto72.Pass AND gvl.Est_Resultados[gvl.PunteroEst].tiempoPass[1] < 1 THEN
	gvl.Est_Resultados[gvl.PunteroEst].tiempoPass[1] :=   TIME_TO_INT(TempCiclo.ET/1000);
ELSIF GVL.Puesto72.Fail THEN
	gvl.Est_Resultados[gvl.PunteroEst].tiempoPass[1] := -1;
END_IF






















]]></ST>
      </Implementation>
    </Action>
    <Action Name="CicloLinea_entry" Id="{ba3e33f5-6fcf-45f5-9190-4764bf44691b}">
      <Implementation>
        <ST><![CDATA[TempCiclo(IN:=FALSE, PT:= DWORD_TO_TIME(  (INT_TO_DWORD(gvl.TiempoDeCiclo) -3)* 1000));
TempRetraso(IN:=FALSE, PT:= T#15M);



gvl.PunteroEst := gvl.PunteroEst +1;
IF gvl.PunteroEst > 1999 THEN
	gvl.PunteroEst := 1;
END_IF


//Creamos un nuevo registros
gvl.Est_Resultados[gvl.PunteroEst].Ciclo := gvl.TiempoDeCiclo;
gvl.Est_Resultados[gvl.PunteroEst].Producto := gvl.Producto;
gvl.Est_Resultados[gvl.PunteroEst].horaInicio := gvl.HoraActual;



FOR puesto := 1 TO 18 DO
	gvl.Est_Resultados[gvl.PunteroEst].tiempoPass[puesto] := 0; 
	gvl.Est_Resultados[gvl.PunteroEst].RetrasoPuesto[puesto] := 0;
	
END_FOR]]></ST>
      </Implementation>
    </Action>
    <Action Name="ComprobarSeguridad" Id="{7bf695df-134b-461a-8076-612d34882cfb}">
      <Implementation>
        <ST><![CDATA[IF NOT SeguridadSetas THEN
	SFCReset:=TRUE;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="ControlDeFallos" Id="{31645b11-331d-4389-8c5f-6526e1dfd6bb}">
      <Implementation>
        <ST><![CDATA[
//Tiempo de fin de ciclo para estadistica
gvl.Est_Resultados[gvl.PunteroEst].horaFin := gvl.HoraActual;

//avanzamos el fallo en el palet y guardamos estadistica
FOR puesto := 18 TO 2 BY -1 DO
	gvl.FalloPallet[puesto] := gvl.FalloPallet[puesto -1 ];
END_FOR

gvl.FalloPallet[1] := Falso;


]]></ST>
      </Implementation>
    </Action>
    <Action Name="EsperaRunStop_active" Id="{1403c2f3-23a7-41d2-8640-6c276ea6723a}">
      <Implementation>
        <ST><![CDATA[FlancoRunStop(CLK:=CuadroPrincipalRunStop);

Gvl.SemaforoAmarillo := TRUE;
MotorCintaSuperior(0);
MotorCintaInferior(0);]]></ST>
      </Implementation>
    </Action>
    <Action Name="Init_active" Id="{92180a6b-d030-4817-b874-17e008391633}">
      <Implementation>
        <ST><![CDATA[MotorCintaSuperior(0);
MotorCintaInferior(0);
SFCreset := FALSE;
gvl.SemaforoAmarillo :=FALSE;
gvl.SemaforoVerde := FALSE;
]]></ST>
      </Implementation>
    </Action>
    <Action Name="ModoRUN_active" Id="{3d03e4c2-a57c-4164-b30e-07c18b64000b}">
      <Implementation>
        <ST><![CDATA[
TempCiclo(IN:=FALSE);

IF ElevadorFinLinea.Ready THEN
 MotorCintaSuperior(1);
END_IF

gvl.SemaforoAmarillo :=TRUE;

IF ElevadorInicioLinea.EsperandoPalet OR ElevadorInicioLinea.Ready THEN
	MotorCintaInferior(1);
END_IF

IF (ElevadorInicioLinea.Ready AND
	ElevadorFinLinea.ready AND 
	GVL.Puesto12.FinPuesto AND
	GVL.Puesto21.FinPuesto AND
	GVL.Puesto22.FinPuesto AND
	GVL.Puesto31.FinPuesto AND
	GVL.Puesto32.FinPuesto AND
	GVL.Puesto41.FinPuesto AND
	GVL.Puesto42.FinPuesto AND
	GVL.Puesto51.FinPuesto AND
	GVL.Puesto52.FinPuesto AND
	GVL.Puesto61.FinPuesto AND
	GVL.Puesto62.FinPuesto AND
	GVL.Puesto71.FinPuesto AND
	GVL.Puesto72.FinPuesto AND
	GVL.Puesto81.FinPuesto AND
	GVL.Puesto82.FinPuesto AND
	GVL.Puesto91.FinPuesto )
THEN		
		gvl.SemaforoVerde := TRUE;
		LineaReady := TRUE;
			
ELSE
			LineaReady:=FALSE;
			gvl.FinTiempo :=FALSE;
			gvl.SemaforoVerde := FALSE;
END_IF

]]></ST>
      </Implementation>
    </Action>
    <Method Name="MotorCintaInferior" Id="{4dd83318-4905-46c4-8553-8aafc8299076}">
      <Declaration><![CDATA[METHOD PRIVATE MotorCintaInferior : BOOL
VAR_INPUT
	Direccion: INT;
END_VAR

]]></Declaration>
      <Implementation>
        <ST><![CDATA[MotorInferior_Freq := gvl.VelocidadCinta * 100;


MotorInferior_Command := 0;
MotorInferior_Command.7 := 1 ; //Control Word Active


IF Direccion  = 0 THEN
	MotorInferior_Command.3 := 1 ; // Stop according to parameter setting	

ELSIF gvl.ElevadorInicioLinea.PresenciaCintaAbajo AND NOT gvl.ElevadorInicioLinea.SensorAbajo THEN
	// presencia en la salida y el elevador no esta abajo: paramos y ERROR
	MotorInferior_Command.3 := 1 ;
	
ELSIF Direccion  = 1 THEN		
		MotorInferior_Command.2 := 1 ; //1 reversed 0 fordward
		MotorInferior_Command.0 := 1 ; // Run Command active
ELSE
	MotorInferior_Command.3 := 1 ; // Stop according to parameter setting	
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Method Name="MotorCintaSuperior" Id="{47a5a076-0660-42e6-aa83-a7b0e8c717a5}">
      <Declaration><![CDATA[METHOD PRIVATE MotorCintaSuperior : BOOL
VAR_INPUT
	Direccion: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[MotorSuperior_Freq := gvl.VelocidadCinta * 100;


MotorSuperior_Command := 0;
MotorSuperior_Command.7 := 1 ; //Control Word Active

IF Direccion = 0 THEN
	MotorSuperior_Command.3 := 1 ; // Stop according to parameter setting	
ELSIF gvl.Elevadorfinlinea.PresenciaCintaArriba AND NOT gvl.Elevadorfinlinea.sensorarriba THEN
	//ERROR : palet en la salida y elevador no arriba
	MotorSuperior_Command.3 := 1 ;
ELSIF Direccion  = 1 THEN		
		MotorSuperior_Command.2 := 0 ; //1 reversed 0 fordward
		MotorSuperior_Command.0 := 1 ; // Run Command active
ELSE
	MotorSuperior_Command.3 := 1 ; // Stop according to parameter setting	
END_IF
]]></ST>
      </Implementation>
    </Method>
    <Action Name="ReseteaPuestos_active" Id="{62f95641-774b-4a26-8ab2-96e7f8af90ad}">
      <Implementation>
        <ST><![CDATA[
//Resetea los puestos para pasar un palet


GVL.Puesto11.SFCreset := TRUE;
GVL.Puesto12.SFCreset := TRUE;
GVL.Puesto21.SFCreset := TRUE;
GVL.Puesto22.SFCreset := TRUE;
GVL.Puesto31.sfcreset := TRUE;
GVL.Puesto32.sfcreset := TRUE;
GVL.Puesto41.sfcreset := TRUE;
GVL.Puesto42.sfcreset := TRUE;
GVL.Puesto51.sfcreset := TRUE;
GVL.Puesto52.sfcreset := TRUE;
GVL.Puesto61.sfcreset := TRUE;
GVL.Puesto62.sfcreset := TRUE;
GVL.Puesto71.sfcreset := TRUE;
GVL.Puesto72.sfcreset := TRUE;
GVL.Puesto81.sfcreset := TRUE;
GVL.Puesto82.sfcreset := TRUE;
GVL.Puesto91.sfcreset := TRUE;
GVL.Puesto92.sfcreset := TRUE;

ElevadorInicioLinea.SFCreset := TRUE;
ElevadorFinLinea.SFCreset := TRUE;
]]></ST>
      </Implementation>
    </Action>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="SFCProperty">
            <n n="SFCErrorAnalyzation" />
            <n n="SFCErrorAnalyzationTable" />
            <v n="Title">"IecSfc"</v>
            <v n="Company">"System"</v>
            <v n="Version">"3.4.2.0"</v>
            <v n="Namespace">""</v>
            <d2 n="Flags" ckt="Flags" cvt="SFCPropertyFlagData">
              <v>EnableLimit</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Init</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Reset</v>
              <o>
                <v n="Use">true</v>
                <v n="Declare">true</v>
              </o>
              <v>QuitError</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Pause</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Error</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Trans</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>ErrorPOU</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>CurrentStep</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>Tip</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>TipMode</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzation</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
              <v>SFCErrorAnalyzationTable</v>
              <o>
                <v n="Use">false</v>
                <v n="Declare">true</v>
              </o>
            </d2>
            <v n="CalcActiveTransOnly">false</v>
            <v n="UseDefaults">true</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="Flags">{27d8150b-ef58-4fff-8da1-1f7dd5f9ea51}</Type>
          <Type n="SFCProperty">{58548d2c-f1b1-453d-9195-66c94e2a3ae0}</Type>
          <Type n="SFCPropertyFlagData">{24565a38-6368-4874-ab9a-0ef7ec269521}</Type>
          <Type n="String">System.String</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="Seguridad.CicloLinea_active">
      <LineId Id="550" Count="58" />
      <LineId Id="630" Count="5" />
      <LineId Id="609" Count="20" />
      <LineId Id="58" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.CicloLinea_entry">
      <LineId Id="2" Count="10" />
      <LineId Id="24" Count="2" />
      <LineId Id="16" Count="7" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.ComprobarSeguridad">
      <LineId Id="2" Count="1" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.ControlDeFallos">
      <LineId Id="2" Count="5" />
      <LineId Id="9" Count="5" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.EsperaRunStop_active">
      <LineId Id="2" Count="3" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.Init_active">
      <LineId Id="2" Count="4" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.ModoRUN_active">
      <LineId Id="2" Count="40" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.MotorCintaInferior">
      <LineId Id="3" Count="19" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.MotorCintaSuperior">
      <LineId Id="3" Count="16" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Seguridad.ReseteaPuestos_active">
      <LineId Id="2" Count="24" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>